[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_todo_list_app = "9Hsv3dV21Xqo2FdZUwU1eQ71eJgbwPgy9rcAQnHQjqd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rodgerschayuga/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
